// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Contributor struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	AvatarURL *string   `json:"avatarUrl,omitempty"`
	Projects  []string  `json:"projects"`
	JoinedAt  time.Time `json:"joinedAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type ContributorInput struct {
	Username  string   `json:"username"`
	Email     string   `json:"email"`
	Name      string   `json:"name"`
	AvatarURL *string  `json:"avatarUrl,omitempty"`
	Projects  []string `json:"projects,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type UpdateContributorInput struct {
	Username  *string  `json:"username,omitempty"`
	Email     *string  `json:"email,omitempty"`
	Name      *string  `json:"name,omitempty"`
	AvatarURL *string  `json:"avatarUrl,omitempty"`
	Projects  []string `json:"projects,omitempty"`
}
